### ISSUE TITLE
How does the transparent proxy work?

### ISSUE THREAD

**Issue by Saren-Arterius** [yrutschle/sslh#100]
I am interested in the transparent proxy feature of sslh. I plan to import a similar feature to any websocket-tcp bridge so that I can use IP based access management while players are accessing my game server through that bridge. Where do I gain such knowledge about the implementation of transparent proxy? Thanks.

**Comment by yrutschle** [comment]
On Sat, Aug 27, 2016 at 09:51:37AM -0700, Saren Arterius wrote:
> I am interested in the transparent proxy feature of sslh. I plan to import a similar feature to any websocket-tcp bridge so that I can use IP based access management while players are accessing my game server through that bridge. Where do I gain such knowledge about the implementation of transparent proxy? Thanks.

Internet searches and looking up examples (netcat, if I
remember correctly).

The basic idea is to bind() to the address of the remote
client instead of an uninitialised address which bind()
sets to a local address.

Basic proxy:
accept() -> gives you a socket connected to the remote client
bind() -> gives you the local part of a socket
connect() -> to the server you're proxying to

Transparent proxy:
accept() -> gives you a socket connected to the remote client
init sockaddr with remote address returned by accept()
bind() with that sockaddr
connect() to the server you're proxying to.


Hope that helps,
Y.

**Comment by yrutschle** [comment]
(closing as this isn't really an sslh issue)

**Comment by Saren-Arterius** [comment]
Thanks! However, it seems that there is lack of IP_FREEBIND support in node.js. Thanks again for your kind explanation.

**Comment by yrutschle** [comment]
On Wed, Aug 31, 2016 at 08:56:56AM -0700, Saren Arterius wrote:
> Thanks! However, it seems that there is lack of IP_FREEBIND support in node.js. Thanks again for your kind explanation. 

Whoa, transparent proxying requireѕ fairly close cooperation
with the kernel, I'm not sure Javascript is the right
environment to do that...

**Comment by Saren-Arterius** [comment]
We almost did it... I think we are just stuck in linux internal networking part.
https://github.com/inDream/wstunnel/commit/afeb64184ff73b0dacaca3e4921088daf1469045

**Comment by Saren-Arterius** [comment]
We did it
https://github.com/Saren-Arterius/wstunnel
