### ISSUE TITLE
HTTP2 support?

### ISSUE THREAD

**Issue by xanview** [yrutschle/sslh#113]
I have enabled http2 in nginx, but requests are still coming as http1.1. Does SSLH support passing http2?

**Comment by yrutschle** [comment]
By my understanding of the specification
(https://http2.github.io/http2-spec/#versioning), it should work:
- If it is over TLS, it'll behave as usual (and you can use
  ALPN to route it)
- If it's clear text, the client should send an HTTP request
  that sslh should recognise as such and forward to nginc,
  and then the client upgrades to HTTP2, but once sslh has
  started forwarding to your nginx it won't touch the
  connection anymore

That said, I've never tried it.

**Comment by jython234** [comment]
I have HTTP2 also enabled in nginx, and also have the same problem that requests are still http/1.1. It turns out the problem is that openssl 1.0.1e, which is what my version of nginx is built with, doesn't support ALPN, only NPN. Google Chrome 51 removed support for NPN and moved on the ALPN. Basically, the browser can't negotiate with the server on which protocol to use, so it just uses HTTP 1.1, and nginx thinks that the browser doesn't support HTTP 2. You can read more about it [here.](https://www.nginx.com/blog/supporting-http2-google-chrome-users/). If you force HTTP 2 (using an online test service such as [this](https://tools.keycdn.com/http2-test)), then it will work, though it notifies you that ALPN is not supported.

OpenSSL 1.0.2 has support for ALPN, but the only OS shipping that right now is Ubuntu 16.10.

**Comment by X-dark** [comment]
Works fine with OpenSSL 1.1.0.f and Nginx 1.12.1

**Comment by xtaran** [comment]
I've just tried to run an Apache 2.4.27 linked against OpenSSL 1.1 and with HTTP/2 enabled behind sslh 1.18 on Debian Testing. If I tried to use an HTTP/2-only client (`nghttp`), it failed to retrieve any contents and aborted with an error message mentioning "failed to upgrade". Without sslh in front, it works on a different machine (running Debian Unstable and the same Apache and OpenSSL versions).

**Comment by yrutschle** [comment]
I think HTTP2 is an entirely different protocol that bears
no resemblance to HTTP (from the packet format point of
view), and that we don't have a probe for it, so it's indeed
not supported.

RFC7540 3.5 specifies the client must first writes "PRI *
HTTP/2[...]" so it should be trivial to write one with the
regex engine, and easy to write a native one in C. I don't
have time right now though :-)

**Comment by gsf** [comment]
Can confirm that it works for now with the ssl protocol and http2-enabled nginx.
