### ISSUE TITLE
IPv6 listen address not recognized in config file

### ISSUE THREAD

**Issue by phi1010** [yrutschle/sslh#128]
I'd like to use the same ports for my web server and sslh by binding them to different IP addresses.
This works fine with IPv4 addresses, but example.cfg does not show any way to make this work, and the obvious candidates neither work.

Using ```{ host: "fe80::1234:1234:1234:1234"; port: "443"; }``` causes sslh to fail upon startup and displays ```myhostname.com:https:bind: Invalid argument``` in the logs.

Using ```{ host: "[fe80::1234:1234:1234:1234]"; port: "443"; }``` allows sslh to start, but displays ```Name or service not known `[fe80::1234:1234:1234:1234]:443'```

Is there a way to let sslh accept IPv6 connections without using inetd?

**Comment by rdebath** [comment]
The addresses `fe80::/16` are link local I think it might be complaining about the address.
For me this line does what I want:
```
    { host: "::"; port: "443"; }
```
It binds to both IPv6 and IPv4 on all interfaces. You get IPv6 addresses in the logs for IPv4 connections, but otherwise it's fine.

If I put the public address in a host field `2001:xxxx:xxxx:xxxx::1` in the config it binds to just that address, as it should.

**Comment by phi1010** [comment]
Thanks, that has been the problem.
