### ISSUE TITLE
fnmatch requires zero terminated strings

### ISSUE THREAD

**Issue by rdebath** [yrutschle/sslh#135]
Commit https://github.com/yrutschle/sslh/commit/6cc33820d166bc790c79f8e42aec8f53bcefd2ba replaces a strncmp with a fnmatch. This means that if the byte after the SNI name in a hello packet is not zero the match will fail. This may also cause a buffer overflow read and possible security issue.

This issue was triggered by the 'palemoon' browser.

**Comment by jmccrohan** [comment]
Thank you for reporting this.

I can recreate this issue using Palemoon, but cannot recreate using Firefox or Chrome. This is due to Palemoon sending the `renegotiation_info` TLS extension immediately after the `server_name` extension. As you can see from [this](https://www.iana.org/assignments/tls-extensiontype-values/tls-extensiontype-values.xhtml#tls-extensiontype-values-1) list of TLS extension types, `renegotiation_info` is the only extension where the upper byte in the header is not `0x00`. All of the other extensions would have acted as a null terminator.

I propose to fix this issue using the patch below. This will `strncpy` the `name` variable containing the hostname to a new string called `name_null` and forcibly null terminate it. `name_null` is then passed to `fnmatch` rather than `name`.

@rdebath @yrutschle: Could you please review?

```
diff --git a/tls.c b/tls.c
index fc4ae38..a31d0b8 100644
--- a/tls.c
+++ b/tls.c
@@ -288,10 +288,13 @@ parse_alpn_extension(const struct TLSProtocol *tls_data, const char *data, size_
 static int
 has_match(char** list, const char* name, size_t name_len) {
     char **item;
+    char name_null[name_len+1]; // sizeof(name) + null char
+    strncpy(name_null, name, name_len);
+    name_null[name_len]='\0'; //ensure name_null is null terminated
 
     for (item = list; *item; item++) {
         if (verbose) fprintf(stderr, "matching [%.*s] with [%s]\n", (int)name_len, name, *item);
-        if(!fnmatch(*item, name, 0)) {
+        if(!fnmatch(*item, name_null, 0)) {
             return 1;
         }
     }
```

**Comment by jmccrohan** [comment]
Ping @rdebath @yrutschle.

**Comment by rdebath** [comment]
Oh, okay.

Yes, that's a suitable fix for the issue.
However:
 * memcpy may be faster than strncpy
 * yrutschle may not wish to use the C99 construct of variable length arrays.
 * It's standard practice NOT to add comments that exactly duplicate the code they attach to.

**Comment by yrutschle** [comment]
ah, I thought I'd read about this somewhere before :-)
Thanks for your patches and feedbacks.
