### ISSUE TITLE
XMPP http_upload

### ISSUE THREAD

**Issue by nordurljosahvida** [yrutschle/sslh#140]
Hi there. Thank you so much for this awesome project.

This is not an issue, but I'd like to know if we can expand the XMPP functionality by also allowing for http_uploads and other connections on different ports to happen as well. I know anything recognizable via regex can be implemented, but I wanted to ask first.

My ejabberd server also listens on ports 5280 and 5444 for http_upload connections.

Any ideas on if and how to get those channeled correctly?

Thanks!

**Comment by yrutschle** [comment]
I'm not sure what you expect from sslh. As far as I understand from a quick look at http_upload, it's the XMPP server sending a URL so the client can PUT (as in HTTP PUT) a file on the server, then gets a URL got GET (as in HTTP GET) that same file: it's all HTTP and should be already covered by the HTTP probes.

**Comment by nikksno** [comment]
Thanks for your reply. The fact is that the HTTP upload module runs on port 5444 [on my ejabberd instance - but it's always a different port than 5222] and SSLH only probes for xmpp-client connections and correctly sends them to port 5222, but it doesn't handle HTTP uploads connections on port 5444, at least without changing something. @moparisthebest mentioned in the ML that as per XEP-0368 there is a way to run all XMPP connections on one single port [5223] [if I understood correctly] and that's what I'm doing now, but I can't get it to work because of several reasons [I don't know how my XMPP client - conversations - handles these connections, it doesn't seem to use the alpn "header" [or whatever it's called], ejabberd doesn't seem to support 0368 yet, and so on. @moparisthebest does XEP-0368 define that all modules, including those running on different ports, can all run on port 5223 if the client is aware of this? @yrutschle back on topic, I think I could simply define that all connections intended for uploads.domain are sent by SSLH on port 5444, but I'm not sure how I'd do that. Thanks and sorry for the off topic.

**Comment by yrutschle** [comment]
On Sun, Nov 05, 2017 at 01:42:19PM +0000, Nicolas North wrote:
> Thanks for your reply. The fact is that the HTTP upload module runs on port 5444 [on my ejabberd instance - but it's always a different port than 5222] and SSLH only probes for xmpp-client connections and correctly sends them to port 5222, but it doesn't handle HTTP uploads connections on port 5444, at least without changing something. 


I am somewhat confused.

Are you trying to run all that behind 443? Meaning:

Client ------> :443 --> sslh ----xmpp----> :5222 ejabberd
                         \-----http------> :5444 ejabberd

This of course implies correct configuration of the ejabberd
http_uload, which needs to listen to 5444 but advertise 443
to the client (which may or may not be possible).

And if http_upload uses https with SNI, you can conceivably
also have a standard https server behind sslh as well.

Y.

**Comment by moparisthebest** [comment]
Assuming your HTTP upload URL is HTTPS (I hope so) you multiplex based on SNI.  If ejabberd cannot have a 'private url' separate from a 'public url' then that is a bug for it to resolve.

For example, ejabberd should say upload to https://upload.example.org/whatever but should actually accept that connection at 127.0.0.1:5444 or whatever you choose, so sslh will send upload.example.org traffic there based on SNI.

**Comment by nikksno** [comment]
@yrutschle yes that's possible, but then I can only advertise port 443 and not let the client choose, but that's completely another problem. @moparisthebest yes absolutely it's HTTPS. I've tested this with:

```
verbose: false;
foreground: false;
inetd: false;
numeric: false;
transparent: false;
timeout: 2;
user: "nobody";
pidfile: "/var/run/sslh/sslh.pid";

# syslog_facility: "auth";

listen:
(
    { host: "hostname.org";       port: "443"; }
);

protocols:  
(
    { name: "ssh"; service: "ssh"; host: "localhost"; port: "22"; keepalive: true; },
    { name: "tls"; host: "localhost"; port: "5223"; alpn_protocols: [ "xmpp-client" ]; },
    { name: "tls"; host: "localhost"; port: "5444"; sni_hostnames: [ "xu.domain.org"]; },
    { name: "tls"; host: "localhost"; port: "443"; },
    { name: "xmpp"; host: "localhost"; port: "5222"; },
    { name: "timeout"; host: "localhost"; port: "443"; }
);
 
on-timeout: "timeout";
```

and it works. As a courtesy, can I ask you to make sure my config is correct from an SSLH standpoint?

@moparisthebest I wouldn't want to further hijack this thread from SSLH matters, but can I ask you how you did it [SSLH config for instance]? What client are you using? I really don't understand if once you use port 5223 all other connections happen on that port or not. How does the client know to override the put_url port and to use 443 instead of 5444?

Thanks to both of you.

**Comment by licaon-kter** [comment]
@nordurljosahvida Maybe you've figured it out already...but since you host the files on `xu.mydomain.tld` you'll setup an entry for that too, and that is just `tls` so it does not have anything to do with XMPP.

In ejabberd you can say `put_url: "https://upload.@HOST@"` or `put_url: "https://xu.@HOST@:443"` so the link sent to the user will be just like that `https://xu.mydomain.tld/something/other/file.ext` or `https://xu.mydomain.tld:443/something/other/file.ext`

BTW, this looks fixed so you might close it.

**Comment by nordurljosahvida** [comment]
@licaon-kter yes thanks, in the end I don't allow the client to choose and I always advertise 443, so things would break if it weren't for SSLH, but we don't need to make them SSLH-independent anyway, so this is ok. I use 5443 for ejabberd_http and that also handles uploads for now [before i switch to nginx] but traffic always comes from 443 via SSLH.
