### ISSUE TITLE
Weirdness while fixing const removal warning 

### ISSUE THREAD

**Issue by rdebath** [yrutschle/sslh#160]
Okay, now this is weird. I was going to see how the `const` warning should be removed so put the `const` flags in to see what was going to break ... but nothing did ... the warning went away and nothing new appeared.

But really, it should be complaining loud an long; the problem is that `strrchr` removes the const qualifier so that `strchr(s,*s)` is basically a cast.

So ... err, do you want it ... um ...

```diff
diff --git a/common.c b/common.c
index 00f9b4f..b0d3050 100644
--- a/common.c
+++ b/common.c
@@ -448,7 +448,7 @@ char* sprintaddr(char* buf, size_t size, struct addrinfo *a)
  *
  * *host gets modified
  **/
-int resolve_split_name(struct addrinfo **out, char* host, const char* serv)
+int resolve_split_name(struct addrinfo **out, const char* host, const char* serv)
 {
    struct addrinfo hint;
    char *end;
diff --git a/common.h b/common.h
index de96633..583c4f7 100644
--- a/common.h
+++ b/common.h
@@ -106,7 +106,7 @@ void drop_privileges(const char* user_name);
 void write_pid_file(const char* pidfile);
 void log_message(int type, char* msg, ...);
 void dump_connection(struct connection *cnx);
-int resolve_split_name(struct addrinfo **out, char* hostname, const char* port);
+int resolve_split_name(struct addrinfo **out, const char* hostname, const char* port);

 int start_listen_sockets(int *sockfd[], struct addrinfo *addr_list);

```

**Comment by yrutschle** [comment]
This is fixed in the last version. I don't think the problem lies in the strrchr(), but rather in the fact that we modify the string indirectly a few lines later:
```
       *end = 0; /* remove last bracket */
```
And the compiler has lost that `end` points to a const string. So when you add the `const` in the prototype, the compiler thinks you satisfy libconfig's requirement, but really you don't. To modify the string the way we do, we need to copy it from libconfig's variables to ours.

**Comment by yrutschle** [comment]
Oh right, you're talking about why C complains while I'm talking about what the code is doing wrong. You're right of course.
