### ISSUE TITLE
SSTP Support?

### ISSUE THREAD

**Issue by grasmanek94** [yrutschle/sslh#166]
Hello, are there any plans for SSTP protocol support? SoftetherVPN, accel-ppp and sorz/sstp-server all offer SSTP server capabilities on Linux. People migrating from IIS+SSTP/Windows could easily use this package to use Their Preffered Web Server+SSTP/Linux.

**Comment by yrutschle** [comment]
I don't know that protocol. A quick glance suggests it's
built on top of TLS, which sslh supports already, so I'd say
(without having tried) that combining the ALPN/SNI probes of
sslh should let you route SSTP as well.

**Comment by grasmanek94** [comment]
Thank you for your quick answer, from what I know SSTP can indeed request a connection to a host via SNI, how would I implement a rule for that? From what I can find you are probably referring to a configuration files like [this](https://github.com/yrutschle/sslh/blob/master/example.cfg#L67) right? so I can make, if hostname requested via sni equals `vpn.domain.com` it would redirect to a specific host:port?

**Comment by yrutschle** [comment]
On Thu, Feb 01, 2018 at 03:01:30PM +0000, Gamer_Z wrote:
>  so I can make, if hostname requested via sni equals `vpn.domain.com` it would redirect to a specific host:port?

Yes that would be the idea: you create a DNS entry for the
SSTP service (e.g. vpn.example.com) then configure sslh to
forward connections to that host to the host:port of your
SSTP server, e.g. localhost:4040, assuming you configure
your SSTP server to listen on 4040.

**Comment by jamesmacwhite** [comment]
@grasmanek94 

Hi. I know this was posted a while ago but did you have any success getting SSTP to work with sslh? Because residential ISPs typically only provide a single IPv4 I have port 80 and 443 forwarded to a Apache reverse proxy so I can run various services using VirtualHosts and SNI. Doing this made me lose the ability to use my Windows Servers SSTP connection, because the domain it ran under was also placed behind this reverse proxy. IIS has the ability to appropriately route SSTP over 443, where as Apache doesn't.

I recently came across sslh and it seemed promising as most solutions mentioned using HAproxy or IIS itself as the reverse proxy, but I'm much more comfortable with Apache and I'd like to keep it.

I've already successfully implemented sslh with my existing Apache setup, but I'm looking for being able to route SSTP traffic to my server with sslh at the edge instead. I'm using it as a transparent proxy currently.

Any advice appreciated if you managed to get it working?!

**Comment by grasmanek94** [comment]
@jamesmacwhite I think I made a separate domain name that I included in my TLS certificate as an alt dns entry. Then I handled the redirection in apache by creating a reverse proxy to the windows sstp host. I think. I forgot / don't know if it actually worked because soon I switched to debian completely.

**Comment by jamesmacwhite** [comment]
@grasmanek94 Thanks for your reply! That's interesting. I figured that sslh would need a rule that bypassed Apache completely and instead sslh with SNI would route the SSTP traffic away from anything Apache and directly to the Windows IIS box locally.

The way I had my Server 2012 R2 Essentials box configured meant the domain I had originally setup on that server, was then configured as a reverse proxy, after doing that, any attempt to connect via SSTP would just get met with 413 error (I could see it in the access logs) because it was hitting the web VirtualHost and Apache didn't understand the request header `SSTP_DUPLEX_POST`. I recently tried configuring a CNAME `vpn.` and setting up a rule with sslh that routed it to the IIS server with SNI, but that didn't seem to work.

Are you saying you still had Apache involved in the process to route the traffic?

**Comment by grasmanek94** [comment]
@jamesmacwhite Well, like I said I don't really remember as this was almost a year ago. I did indeed run into lots of issues and remember the number 413 unfortunately a bit too good.. I eventually settled on OpenVPN with sslh (though some DPI FWs' still block OpenVPN even in TCP mode on port 443). I think I went as far as capturing tcpdumps on both sides (client server) when SSTP works and comparing those with sslh and Apache reverse proxy configurations and trying to work my way up from there. That's what I would do again today if I wanted to use SSTP.

**Comment by jamesmacwhite** [comment]
@grasmanek94 No worries. I can understand if it was a while ago it's difficult to remember network stuff like this. I'm at the point now where I might just have to abandon SSTP, it sounds like I could end up going down a rabbit hole! Given sslh works with OpenVPN I may try that instead. I run DD-WRT on my Netgear R7000 and could run a VPN server from that. Deep Packet Inspection shouldn't be an issue for the networks I would use a VPN on, but good to know!

I certainly appreciate your advice/previous experience on this!
