### ISSUE TITLE
Shadowsocks proxy rules

### ISSUE THREAD

**Issue by ram108** [yrutschle/sslh#191]
Is it possible to add protocol rules for Shadowsocks proxy? It is a good alternative to OpenVpn and used very intensively.

URL: https://github.com/shadowsocks/shadowsocks-libev
SITE: https://shadowsocks.org

**Comment by yrutschle** [comment]
Considering this bit of the documentation:

> ss-local initiates a TCP connection to ss-remote by sending an encrypted data stream starting with the target address followed by payload data. The exact encryption scheme differs depending on the cipher used.


I would expect it not doable as `sslh` would need to decipher first to do any probing.

**Comment by Codelica** [comment]
Also ShadowSocks seems to get identified as SSL for some reason, at least for me using this SSLH 1.18 container (https://hub.docker.com/r/shaddysignal/sslh-hub/) which leaves ShadowSocks to get picked up by the "anyprot" option.  I tried several ShadowSock encryption methods, but they all seemed to be identified as SSL for some reason.  Testing with the Outline client on Mac.

**Comment by yrutschle** [comment]
> Also ShadowSocks seems to get identified as SSL[...] ShadowSocks to get picked up by the "anyprot" option

This is contradictory, ssl and anyprot are not the same probes.

**Comment by yrutschle** [comment]
(I'm adding a 'wontfix' status, though the current status is more like 'impossible')

**Comment by 132ikl** [comment]
I'm having the same issue. ShadowSocks doesn't seem to work *at all* over sslh, even using `anyprot`. SSH and Nginx work fine.

Running ShadowSocks on 127.0.0.1:7688, using this sslh config;
`DAEMON_OPTS="--user sslh --listen 0.0.0.0:443 --anyprot 127.0.0.1:7688 --pidfile /var/run/sslh/sslh.pid"`

ShadowSocks using the same config but on the server domain instead of 127.0.0.1 works fine.

**Comment by tombii** [comment]
I'm using shadowsocks-libev 3.2.0 (aes-256-cfb) together with sslh 1.16-2 with the anyprot option. It works but is slow since sslh is forking one process per request (my browser is set to 16 threads I think).
I think sslh-select would be a better fit. I might take the time to compile the latest version of sslh-select and try it. Debian Jessie doesn't come with anything newer than 1.16-2.

**Comment by aidaho** [comment]
SSLH 1.18-1 works like intended with `--anyprot` pointing to shadowsocks-libev:

    optiplex sslh[10824]: anyprot:connection from xxx.xxx.xxx.xxx:15221 to 192.168.0.50:https forwarded from localhost:55572 to localhost:8388
