### ISSUE TITLE
X-Forwarded Proto

### ISSUE THREAD

**Issue by Koma-Andrea** [yrutschle/sslh#251]
Hi, I know that the issue #13 already replied to this question but I was wondering if maybe today you changed idea on that.

Do you think it is possible to inject an header on top?

The main problem is that using  sslh in a containerised environment makes really hard using the transparent way, the ports are binded by docker-proxy and using hosts network is tipically a bad idea.

**Comment by yrutschle** [comment]
I am not sure how that would help: either sslh has access to the original IP and its --transparent option should work, or it can't get to the IP because it's bound by docker-proxy, and it won't be able to fill in the header.

It just might be that using containers is a bad idea :-) (I am somewhat unconvinced by Docker's benefits)

**Comment by Koma-Andrea** [comment]
Well I work in Red Hat on the OpenShift team, so I'm firmly convinced about the benefits of the containerization :)
That said you are right about the rest. Didn't realized the limitation.
