### ISSUE TITLE
Transparent proxy not quite working

### ISSUE THREAD

**Issue by csarn** [yrutschle/sslh#252]
Hi,

I tried to set up sslh as described here:
http://rutschle.net/pipermail/sslh/2018-April/000674.html
What works:
- if I set transparent to false, and do NOT set up the the ip routing rules, I can connect to my httpd (as expected)
- if I set transparent to true, and do still NOT set up the ip routing rules, I can no longer connect (as expected, with transparency, the httpd should try to send to an address it can't reach, as far as I understand)
- if I set transparent to true, and DO set up the routing rules, connection works again (as expected)
  BUT in this case the access log of my httpd (nginx) still logs my local address (192.168.xxx.xxx) as the remote ip, even though wireshark shows TCP packets going from 127.0.0.2 to 2.247.xxx.xxx, which is the remote address I'm connecting from.
A similar thing happens on SSH. I can login via ssh to port 443 (through transparent sslh), but ssh shows my login coming from the local IP address again. Wireshark shows here that sshd sends its packets to 127.0.0.1.

I don't understand how this happens. And as the ip routing setup (or the iptables setup mentioned in the docs) only affect the outgoing packets from sshd/httpd, this behaviour is not due to me choosing ip rules vs iptables, right? So something goes wrong in sslh?

I have the same behaviour with sslh 1.18 from debian, and 1.20 from master branch (bae16ab29e).

**Comment by sblantipodi** [comment]
same here, 
transparent seems broken.

please fix or create a guide on how to use it, in the current state is unusable

**Comment by geek85** [comment]
I can add some hints:
with sslh-fork 1.18-1 (on debian buster)
SSLH on 192.168.1.100 :

- with SSHD on same host: transparent proxy works. `who am i` shows the correct IP

- with nginx into a docker container on 192.168.1.100, connexion OK but ip is not the client IP but the gateway IP of Docker (172.19.0.1) 

- Same with openvpn on docker: 172.19.0.1 as incoming IP

the IPtables rules are the ones from [config.md](https://github.com/yrutschle/sslh/blob/master/doc/config.md)
`# Set route_localnet = 1 on all interfaces so that ssl can use "localhost" as destination
sysctl -w net.ipv4.conf.default.route_localnet=1
sysctl -w net.ipv4.conf.all.route_localnet=1

# DROP martian packets as they would have been if route_localnet was zero
# Note: packets not leaving the server aren't affected by this, thus sslh will still work
iptables -t raw -A PREROUTING ! -i lo -d 127.0.0.0/8 -j DROP
iptables -t mangle -A POSTROUTING ! -o lo -s 127.0.0.0/8 -j DROP

# Mark all connections made by ssl for special treatment (here sslh is run as user "sslh")
iptables -t nat -A OUTPUT -m owner --uid-owner sslh -p tcp --tcp-flags FIN,SYN,RST,ACK SYN -j CONNMARK --set-xmark 0x01/0x0f

# Outgoing packets that should go to sslh instead have to be rerouted, so mark them accordingly (copying over the connection mark)
iptables -t mangle -A OUTPUT ! -o lo -p tcp -m connmark --mark 0x01/0x0f -j CONNMARK --restore-mark --mask 0x0f

# Configure routing for those marked packets
ip rule add fwmark 0x1 lookup 100
ip route add local 0.0.0.0/0 dev lo table 100`

So these rules seem to work for services on the same host but not for docker ones.
I also tested with rules from [this post](https://superuser.com/questions/1326592/how-to-set-up-sslhs-transparent-mode-in-a-docker-environment) but no luck.

**Comment by yrutschle** [comment]
Ok that's interesting... so I gather we have (at least) 4 different settings:

- sslh and target service on same host
- sslh and target service on different hosts
- sslh on main host and target in a docker on the same host
- sslh in a docker targeting a different docker

I think I'll clean up the documentation to clarify what is supposed to work in which situation, and clear up that we have no working rules for docker setups...

**Comment by tharrrk** [comment]
I think that most of info **IS** actually in the [README](https://www.rutschle.net/tech/sslh/README.html).

What is a bit confusing at first as per this doc is the need for another "virtual" ip on the eth device (not lo) for marking the returning packets, and routing it via table 100 to `sslh` process (not directly to the network client). That's because `sslh` replaces that back with the "public" ip when sending the packet back AFAIK.

So let's say we have very basic 2 services setup we want to multiplex onto port 443 = httpd and ssh (adjust for nginx etc).
For clean operation (as I understand it) we need 1 "public" IP, 1 "virtual" IP, both on eth device (`ip addr add x.x.x.x/32` the "virtual" one) and both services running on a "virtual" ip (at least).
If a service is required to be accessible on its usual port (i.e. sshd on tcp/22) it has to listen on two endpoints - "public":22 and "virtual":another_port.

Now one can configure sslh.cfg to access those two sevices on a "virtual" ip and set up `iptables`, `ip route` and `ip rule`s in a way that's not interfering with it's usual endpoint.

**Example:**

public_ip = `1.2.3.4/16`
virtual_ip = `10.0.0.1/32`

In sshd_config:
Usual endpoint...
```
Port 22
ListenAddress 0.0.0.0
ListenAddress ::
```
Virtual endpoint...
```
ListenAddress 10.0.0.1:8022
```
In httpd.conf (`1.2.3.4:443` is where we want multiplexing to happen so that's not an option):

```
Listen 80
Listen 8443
```
_+ all that VirtualHost, NameVirtualHost and ssl stuff as needed..._

So what you end up with (check with `netstat -anp|grep ^tcp.*LISTEN`) is:
```
tcp        0      0 0.0.0.0:22          0.0.0.0:*        LISTEN      10000/sshd
tcp        0      0 10.0.0.1:8022       0.0.0.0:*        LISTEN      10000/sshd
tcp        0      0 :::80               :::*             LISTEN      20000/httpd
tcp        0      0 :::22               :::*             LISTEN      10000/sshd
tcp        0      0 :::8443             :::*             LISTEN      20000/httpd
```

Now in `sslh.cfg` transparent mode is enabled and services endpoints defined:
```
transparent: true;
```
...
```
listen:
(
    { host: "1.2.3.4"; port: "443"; }`
);

protocols:
(
     { name: "ssh"; service: "ssh"; host: "10.0.0.1"; port: "8022"; probe: "builtin"; },
     { name: "http"; host: "10.0.0.1"; port: "80"; probe: "builtin"; },
     { name: "ssl"; host: "10.0.0.1"; port: "8443"; probe: "builtin"; }
);
```

On my (painfully old) CentOS I just put the `iptables`/`ip` stuff inside `/etc/sysconfig/sslh` as that is being simply sourced from the init script:
...
```
# If transparent mode is enabled, the following
# is needed in order to run as sslh user
#
SSLH_USER=sslh
setcap cap_net_bind_service,cap_net_admin=+ep $SSLH

if [ "$1" = "start" -o "$1" = "stop" -o "$1" = "restart" ]; then

# Clean up before start/stop/restart
iptables -t mangle -F SSLHMARK 2>/dev/null && {
  iptables -t mangle -F SSLHCHECK
  iptables -t mangle -D OUTPUT    -o eth0               -j SSLHCHECK
  iptables -t mangle -X SSLHMARK
  iptables -t mangle -X SSLHCHECK
  ip route del local 0.0.0.0/0 dev lo table 100
  ip rule del fwmark 0x1 lookup 100
  ip addr del 10.0.0.1/32 dev eth0
}

[ "$1" = "start" -o "$1" = "restart" ] && iptables -t mangle -N SSLHMARK && {

  # Set up - start/restart only
  iptables -t mangle -N SSLHCHECK
  iptables -t mangle -A SSLHCHECK -p tcp --sport 8022   -j SSLHMARK
  iptables -t mangle -A SSLHCHECK -p tcp --sport 8443   -j SSLHMARK
  iptables -t mangle -A SSLHCHECK                       -j RETURN

  iptables -t mangle -A SSLHMARK                        -j MARK --set-mark 0x1
  iptables -t mangle -A SSLHMARK                        -j RETURN

  iptables -t mangle -A OUTPUT    -o eth0               -j SSLHCHECK

  ip addr add 10.0.0.1/32 dev eth0
  ip rule add fwmark 0x1 lookup 100
  ip route add local 0.0.0.0/0 dev lo table 100
}
```
_Please note that this part should only be adjusted when_ `sslh` _is_ **stop**_ed or one might end with a great mess in_ `iptables` _that needs to be sorted manually (or in a windows way..)_

I hope I didn't forget anything important :)

**Outstanding issue:**
You can't access `1.2.3.4:8443` directly.

I believe this could be sorted with `conntrack` module of `iptables`.

I came up with this:
_Set up phase..._
```
  iptables -t mangle -A INPUT    -i eth0 ! -d 10.0.0.1 -j CONNMARK --set-mark 0x1
  iptables -t mangle -I SSLHMARK -m connmark --mark 0x1 -j RETURN
```

This marks the connection (CONNMARK is different from a MARK target and thus the mark itself is different and 0x1 value can be reused) if it is initiated directly onto our "public" IP which means it's a proper network client connecting and not `sslh`.
Then a rule #1 is inserted into `SSLMARK` chain that skips marking if the connection has been marked.

INPUT chain needs to be cleaned in a same manner as the rest up of course - `iptables -t mangle -D INPUT  -i eth0 ! -d 10.0.0.1 -j CONNMARK --set-mark 0x1`
(Just add to the cleanup part)

Furthermore, I believe it could even **simplify all the above** (get rid of the second IP, secondary ports, blah blah...)
One would basically point `sslh` onto "public" IP and usual port and that's it.

Haven't had a chance to run full test suite on test/prod yet but it seems promising so far. At least both `https://...:443` and `https://...:8443` are accessible.

Hope this helps someone.

**Comment by yrutschle** [comment]
Thanks for the long post. I still don't get the `iptables` magic, but I guess I'm a lost cause (I get the feeling I need to understand the implementation to understand what the commands actually set up).

What do you mean by 'virtual IP'? An additional IP assigned to an Ethernet interface?

Also, have you tried this method that was discussed on the mailing list a few month ago: 
http://rutschle.net/pipermail/sslh/2019-October/000702.html

**Comment by darkfader** [comment]
I was struggling with transparent mode as well. But got it working for IPv4 somewhat at least.
I used 127.0.0.100 so I could filter it out instead on process/user etc. This extra filter makes sure you can still bypass sslh on public IP address and connect directly to SSH, so it is not mandatory.
My port 434/80 is bound to a haproxy-certbot instance.

Part of my docker-compose file:
```
image: riftbit/sslh:debian-select
network_mode: host
environment: -SSLH_OPTS=-p 0.0.0.0:443 -ssh 127.0.0.100:22 -openvpn 127.0.0.100:1194 -tls 127.0.0.100:434 --transparent
```
`/etc/rc.local`
```
#!/bin/sh
iptables -t mangle -N SSLH
iptables -t mangle -A SSLH --jump MARK --set-mark 0x1
iptables -t mangle -A SSLH --jump ACCEPT

iptables -t mangle -A OUTPUT -p tcp -o ens3 -s 127.0.0.100 --sport 22 -j SSLH
iptables -t mangle -A OUTPUT -p tcp -o ens3 -s 127.0.0.100 --sport 434 -j SSLH
exit 0
```

`/etc/sysctl.d/60-sslh.conf`
```
net.ipv4.conf.default.route_localnet = 1
net.ipv4.conf.all.route_localnet = 1
```

`/etc/netplan/60-sslh.yaml`
```
network:
  version: 2
  renderer: networkd
  ethernets:
    all:
      match:
        name: veth*
      routing-policy:
        # ip rule add fwmark 0x1 lookup 100
        - to: 0.0.0.0/0
          table: 100
          mark: 1
        # ip -6 rule add fwmark 0x1 lookup 100
        - to: ::/0
          table: 100
          mark: 1
    lo:
      match:
        name: lo
      routes:
        # ip route add local 0.0.0.0/0 dev lo table 100
        - to: 0.0.0.0/0
          scope: host
          table: 100
        # ip route add local ::/0 dev lo table 100
        - to: ::/0
          scope: host
          table: 100
```

**Comment by iamdoubz** [comment]
What are the implications of using `sslh-select` with user `nobody` binding with on-localhost ip address (given the your router dishes out IPs in the range of 192.168.100.1) of 192.168.100.11, transparent set to `true` in the `/etc/sslh.cfg` file, and [using this](http://rutschle.net/pipermail/sslh/2019-October/000702.html "Source of below commands"):

```
ip rule add from 127.0.0.1 lookup 100
ip route add local 0.0.0.0/0 dev lo table 100
```

This works __perfectly__ for transparency but I have some worries about the security implications it presents.

**Comment by tharrrk** [comment]
Hi again!

> What do you mean by 'virtual IP'? An additional IP assigned to an Ethernet interface?

Yes, exactly that.

> Also, have you tried this method that was discussed on the mailing list a few month ago:
> http://rutschle.net/pipermail/sslh/2019-October/000702.html

Kind of..
I haven't tested it thoroughly but at first sight I was worried in the same way guys in the mailing list and @iamdoubz here above.
Think you have two services using tcp to connect on the same box and you really want to make sure the packet never leaves the box. Postfix+openDKIM as an example.

I'm no such expert to say what exactly happens.
Will the packet arrive fine from postfix to opendkim and back and not leak out?
I'm worried the rule is simply too wide.
If this was something so beneficial why wouldn't it be set by default?
Could this have more security implications where ordinary users access the server?
With additional/virtual IP and fwmark/connmark there seems to be finer grained control.
I might be wrong though with just a false feeling of security :)

**Comment by darkfader** [comment]
After upgrading to Ubuntu 20, the SSLHCHECK/SSLHMARK thing didn't work anymore somehow. I tried going back to the old method, but no traffic between dockers anymore (via public addresses). We need an expert for this.

**Comment by yrutschle** [comment]
If anyone is still hung on this issue, please check this https://github.com/yrutschle/sslh/discussions/454 out. I assume it'll solve the issue, otherwise please create a new one.
