### ISSUE TITLE
[question] http client sometimes gets the ssh banner

### ISSUE THREAD

**Issue by kcris** [yrutschle/sslh#348]
Hi @yrutschle and all other contributors

First of all, thanks for all this effort you put into sslh. I am a happy user, I am using it for years now and it's a great tool.

I have a question

I am using sslh (1.20 on ubuntu) to multiplex ssh/http(s).

Sometimes, rarely, like 1/100 calls, an http client gets the ssh banner. Which (I guess) means that sslh guessed the wrong type of client. It sent the http client to the sshd server (instead of my nginx). Again, 99% of time this works correctly. I was just wondering what could possibly be the cause for this. I know that detection used to work based on timeouts (not super reliable maybe?), then I read that it is based on regexes, so I am not sure about this.

Thank you!

A+
Chris

**Comment by licaon-kter** [comment]
Config?

**Comment by kcris** [comment]
I have two sslh instances

one listening on the public ip/port
```
RUN=yes
DAEMON=/usr/sbin/sslh
DAEMON_OPTS="--user sslh --listen MY-PUBLIC-IP:80 --ssh 127.0.0.1:22 --http 127.0.0.1:9080 --pidfile /var/run/sslh/sslh.pid"
```


and a second one, which comes from stunnel4 (which strips SSL then connects to 2nd sslh instance):
```
RUN=yes
DAEMON=/usr/sbin/sslh
DAEMON_OPTS="--user sslh --listen 127.0.0.1:9443 --ssh 127.0.0.1:22 --http 127.0.0.1:80 --pidfile /var/run/sslh/sslh2.pid"
```

Thanks @licaon-kter

**Comment by utoni** [comment]
The `1.20` release is from 2018, but nothing changed in SSH and HTTP probes. So it should work.
Can you try the `-v -f` options, start it from your terminal, redirect `stderr` to a logfile and upload the logfile here?

**Comment by kcris** [comment]
cannot reproduce now, I will kepp this in mind and see if it happens again. Closing for now, will reopen if needed. Thank you!

**Comment by yrutschle** [comment]
You usually get to ssh in one of two ways: either the client starts by sending an ssh banner ("SSH-2.0 ..." ), OR the client sends nothing at all because it's waiting for the server to send that banner. So, `sslh` will connect connections which client sends nothing to ssh after a timeout (`timeout` in the configuration file).

So, what might be happening is that "sometimes", your remote browsers take too long to send the TLS handshake, and get connected to ssh. That can happen on congested networks and busy servers.

**Comment by kcris** [comment]
yes, quite likely that's the problem, it would explain the rare occasions when I saw this.
thanks!!
