### ISSUE TITLE
[SOLVED] Transparent to Nginx on the same host + two different backend-servers (timeout)

### ISSUE THREAD

**Issue by netw0rk-noob** [yrutschle/sslh#371]
I've tried to implement / adapt the tutorial by Sean Warner (https://github.com/yrutschle/sslh/blob/master/doc/tproxy.md#transparent-proxy-to-two-hosts) to my needs without success.
The network / forwarding setup described below works perfectly fine with the transparent option disabled, but that makes it impossible to use services like fail2ban (at least for the backend servers as far as I understand).

Three (**unprivileged**) lxc containers on my Hypervisor (Proxmox Virtual Environment):
- `LXC A`: `192.168.178.143` - sslh (Port `443`), Nginx reverse proxy for https (Port `4443`) used for relaying different https traffic to different backend webservers
- `LXC B`: `192.168.178.130` - prosody (Port `5223`)
- `LXC C`: `192.168.178.145` - openvpn (Port `443`)
- I send traffic from the internet to my router's external port `443` then use a port forward rule in my router to map that to internal port `443` where sslh is listening.

My Network setup, described as in Seans Tutorial:
![SSLH](https://user-images.githubusercontent.com/120289511/206884943-39ec0588-60e8-49e8-98bd-14c62ab4d0b6.svg)

contents of my `/etc/sslh.cfg` (works fine if I set transparent to false):
```
verbose: 2;
foreground: false;
inetd: false;
numeric: true;
transparent: true;
timeout: 2;
user: "root";
pidfile: "/var/run/sslh/sslh.pid";
syslog_facility: "auth";

listen:
( 
    { host: "192.168.178.143"; port: "443"; } 
);

protocols:
(
    { name: "tls"; host: "192.168.178.130"; port: "5223"; alpn_protocols: [ "xmpp-client" ]; log_level: 1;},
    { name: "openvpn"; host: "192.168.178.145"; port: "443"; log_level: 1;},
    { name: "tls"; host: "localhost"; port: "4443"; log_level: 1;},
    { name: "anyprot"; host: "localhost"; port: "4443"; log_level: 1;}
);

on-timeout: "timeout";
```
Regarding the `user:` option I tried using  `user: "root";` and `user: "sslh";` and got the exact same results. 

contents of `/usr/local/sbin/set-sslh-iptables-rules.sh` on `LCX A` (runs without complaining)
```
iptables -t mangle -N SSLH
iptables -t mangle -A PREROUTING -p tcp -m socket --transparent -j SSLH
iptables -t mangle -A OUTPUT --protocol tcp --out-interface eth0@if448 -m multiport --sport 443,4480 --jump SSLH
iptables -t mangle -A SSLH --jump MARK --set-mark 0x1
iptables -t mangle -A SSLH --jump ACCEPT
ip rule add fwmark 0x1 lookup 100
ip route add local 0.0.0.0/0 dev lo table 100
```

contents of `/usr/local/sbin/set-sslh-iptables-rules.sh` on `LXC B` (runs without complaining)
```
iptables -t mangle -N SSLHSSL
iptables -t mangle -A OUTPUT -o eth0 -p tcp -m multiport --sport 5223 -j SSLHSSL
iptables -t mangle -A SSLHSSL --jump MARK --set-mark 0x1
iptables -t mangle -A SSLHSSL --jump ACCEPT
ip rule add fwmark 0x1 lookup 100
ip route add default via 192.168.178.143 table 100
ip route flush cache
```
I changed the interfaces, the ports of the respective services and the LAN ip addresses to suit my network setup.
(same with `LXC C`...)

The behaviour I'm seeing with this setup:
HTTPS-Requests to my backend webservers through Nginx are working, including transparency.
example output of `journalctl --unit sslh.service --reverse` when accessing one of my webpages:
```
Dec 10 20:53:44 LXC-A sslh[446]: tls:connection from <IP>:52552 to 192.168.178.143:443 forwarded from <IP>:52552 to 127.0.0.1:4443
Dec 10 20:53:44 LXC-A sslh[446]: connecting to 127.0.0.1:4443 family 2 len 16
Dec 10 20:53:44 LXC-A sslh[446]: probing for tls: PROBE_MATCH
Dec 10 20:53:44 LXC-A sslh[446]: probing for openvpn: PROBE_NEXT
Dec 10 20:53:44 LXC-A sslh[446]: probing for tls: PROBE_NEXT
Dec 10 20:53:44 LXC-A sslh[446]: Unknown ALPN name: http/1.1
Dec 10 20:53:44 LXC-A sslh[446]: matching [http/1.1] with [xmpp-client]
```

Requests to the other LXCs (in this case prosdoy / `LXC B`, but I get the same response with openvpn / `LXC C`) however are timing out, though being detected correctly. No connection to prosody is being established, according to its verbose log. (I'm using this tls probe for XMPP, because the xmpp probe seems to only detect STARTTLS-encrypted connections, no direct TLS-encrypted ones. It works when used without transparency.)
example output of `journalctl --unit sslh.service --reverse` when trying to connect to my prosody server:
```
Dec 10 20:39:09 LXC-A sslh[379]: connection closed down
Dec 10 20:39:09 LXC-A sslh[379]: client socket closed
Dec 10 20:38:39 LXC-A sslh[382]: connecting to 192.168.178.130:5223 family 2 len 16
Dec 10 20:38:39 LXC-A sslh[382]: timed out, connect to tls
Dec 10 20:38:37 LXC-A sslh[381]: connecting to 192.168.178.130:5223 family 2 len 16
Dec 10 20:38:37 LXC-A sslh[381]: probing for tls: PROBE_MATCH
Dec 10 20:38:37 LXC-A sslh[381]: matching [xmpp-client] with [xmpp-client]
```

Tutorials/Docs I found when searching for a solution and tried to adapt/implement:
https://community.hetzner.com/tutorials/prosody-debian9#optional-advanced-features
https://wiki.mattrude.com/SRV_records_for_XMPP_over_TLS#Configuring_SSLH_for_XMPP_and_HTTPS_Traffic

According to yet another tutorial I found online I tested if anything of that connection even reaches `LXC B`:
output of `netstat -nat | grep 5223` on `LXC A`:
```
tcp        0      1 <IP>:46200     192.168.178.130:5223     SYN_SENT
tcp        0      1 <IP>:46194     192.168.178.130:5223     SYN_SENT
tcp        0      1 <IP>:46198     192.168.178.130:5223     SYN_SENT
tcp        0      1 <IP>:46204     192.168.178.130:5223     SYN_SENT
tcp        0      1 <IP>:46192     192.168.178.130:5223     SYN_SENT
tcp        0      1 <IP>:46206     192.168.178.130:5223     SYN_SENT
```

output of `netstat -nat | grep 5223` on `LXC B`:
```
tcp        0      0 0.0.0.0:5223             0.0.0.0:*      LISTEN
tcp        0      0 192.168.178.130:5223     <IP>:46200     SYN_RECV
tcp        0      0 192.168.178.130:5223     <IP>:46198     SYN_RECV
tcp        0      0 192.168.178.130:5223     <IP>:46206     SYN_RECV
tcp6       0      0 :::5223                  :::*           LISTEN
```

To me (as an absolute networking noob) this looks as if the connection somehow does reach `LXC B` but doesn't reach prosody (which - with verbose logging enabled - does not register anything on connection try). I tried this via mobile phone network (to have a public IP which is different than the one the server is running on) and did see that IP in the oputput of `netstat -nat | grep 5223` though, so I'd say transparency seems to work, which would point to a routing/firewalling problem on `LXC B`? Still the XMPP Client isn't able to connect.
I tried to understand/analyze the iptables/routing commands to be able to alter them/try around, but as I've got only very limited network knowledge and nearly no experience with plain iptables at all I didn't manage to.

Reasons I suspect why it doesnt work, but didn't accomplish to confirm neither rule out by myself:
- me making some mistakes while trying to adopt Seans tutorial to my specific network setup, most likely regarding the iptables/routing script
- all systems running inside **unprivileged** lxc containers, therefore having insufficient permissions for some of the netfilter/iptables/routing stuff
- I didn't compile sslh from source as Sean did but used the version (`1.20-1`) in the repositories of `debian 11 bullseye` - which is running inside of all involved lxc containers.

**EDIT:** To rule out two of these reasons as the cause of my problem I did compile the current version (`sslh-fork v2.0-rc1-36-g40c616e-dirty`) inside of a freshly created virtual machine using the same Makefile options Sean documented in his tutorial - still the same problem: `Connection timed out`.  Therefore I'd pin it down to some sort of iptables / routing misconfiguration.

I'd really appreciate someone with a better understanding of networking, routing and iptables to take a look at this setup to see if I did any obvious mistakes  trying to adapt Seans setup for my usecase. If any needed information is missing, please ask for it and I will add it.
Thanks for any hint, as I'm at my wit's end right right now.

**Comment by kganczarek** [comment]
@netw0rk-noob hi, where you able to figure out how to configure it?

**Comment by yrutschle** [comment]
> appearently no one cares

Thanks for the kind feedback.
As indicated in the documentation, basically *all* transparent proxying issues posted here are not in fact issues with `sslh`, rather with the networking setup around it, and indeed no one seems to understand the `iptables` setup well enough to explain how or why it should work.

The documentation included in the repo is something that worked for someone at some point. As also indicated in the documentation, there are plenty of factors that might require changes to the setup.

With that in mind, the only approach I can suggest is:
- Reproduce exactly Sean's setup. Does not work? Maybe has something to do with the versions (not `sslh`' s version: iptables, kernel, and everything around it).
- If that works, move it to unprivileged LXC. Does not work? We can investigate what capabilities the LXC need (and add it to the documentation)
- If that works, change the network setup.

All that being said, please post back if you find a working alternative (as I think the issue is not with sslh: if you find a way to set up transparent proxying with something else, it might very well work with sslh as well, and as you noticed, I'm happy to add to the current documentation)

**Comment by yrutschle** [comment]
Thanks for the long and constructive feedback (this time with no sarcasm).

I won't address all your points, as I have still nothing to add to the technical parts... Regarding some others (re-ordered for coherence of my discourse):


You explained the thought process that brought you to your state of mind. I have to clarify mine when I read a transparent proxy issue: "here I am, a C programmer progamming C. Oh, here is yet another transparent proxy issue [As you noted, probably about half of posted issues are tproxy ones] where I don't understand the first thing about that business of marking packets. Well at least this one has a lot of technical details, hopefully someone can help. Oh, here's a shiny issue with a segfault, I know C, I'll do that!"

Your non-polemic question is an interesting one. Clearly there is a gradation of whether issues belong on this specific Github. One end of the spectrum is "sslh crashes when it receives two connexions at the same time" (clearly belongs). The other end of the spectrum is "I unzipped the code on a Win98 machine, which we still use in my factory, and when I type `make` it fails." (clearly does not belong).

In that spectrum, I'd say "internal configuration" ("how do I create a SNI-matching rule with globs?") does, "external configuration" ("where do I change configuration on RedHat Linux?") doesn't. The transparent proxy stuff is... well I don't know. It mostly doesn't bother *me* that the issues are there, but mostly *I* can't answer them. More to the point, I am not sure what a better place to ask would be, so... why not here.


Now, I understand your frustration at the documentation. It's very possible you embarked upon your configuration trip when the disclaimers were not present, and I added them precisely faced with the stream of configuration issues posted on that topic. What I can do, is indeed clarify the disclaimer in `config.md` indicated that it's not merely "complicated". Building from your suggestion:

> Configuration of transparent proxying is highly dependent on your network environment and infrastructure setup. There is no known generic approach, and if you do not find directions for your exact setup, you will probably need an extensive knowledge of network management and iptables setup". 

I would say the disclaimer in `tproxy.md` is enough.


I'm unsure about removing "transparent proxying"  from the feature list. As I said (and I'll stand by that), `sslh` itself supports it (the C is actually simple and the underlying concept is easy to understand from the application point of view: you just bind your local socket to the foreign address) and it's the supporting environment that's causing problems. You wouldn't argue to remove "capabilities dropping" because your operating system didn't support capabilities...

As it is, I propose to add the disclaimer above in the README and leave 'transparent proxying' as an advertised feature.

Thanks for the time you are taking to write on this issue, anyhow.

**Comment by yrutschle** [comment]
Disclaimer added in 7ca567f.

> I just assumed that you inevitably had to have a great deal of knowledge in this field to be able to write/maintain a networking tool like sslh.

No, programming C servers and advanced networking are really two different jobs. I also have shortcomings in modern containerisation technologies (notably Docker), and continuous testing pipelines. Of all these, it's the latter I'm most likely to spend time on, but it's also linked to Docker, and just too much to pick up as a side project for the moment...

**Comment by yrutschle** [comment]
Someone found another way to provide transparent proxying, which does not rely on iptables and seems quite a little more straightforward. It's been commited in 8271db2, you may want to check it out (I haven't tried it yet).

**Comment by ftasnetamot** [comment]
I added another document, where I try to show in three scenarios all possible solutions.  All interfaces you need, are shown in the examples.  I can't tell you anything about your ip addresses, but the core rule to all scenarios is:  the hidden services, I refer to them as sshd in all examples, need a unique ip address, which is not used for any other services. As long, as the hidden services are on the same host, residing on dummy0, a /32 ip-address is the solution.
In case you are routing to another host, you need either a second ip from the network, the interface resides, where the target services are binding to. Or you can setup a /30 network with any addresses from the private ranges, where you have two host besides network and broadcast.  But that is all ip and routing basics, and has nothing to do with sslh.  So from my side: You need a unique ip address, which can be connected from the sslh host. 
In your opening example from this thread, you need **TWO** uniqe ip addresses, for prosody and openvpn. When your hosts are not connected on other ways to the internet, both will be scenario 2. You need nothing special on those hosts, but the unique ip for the services.

in the sslh host you need now **THREE** instead **TWO** entries for deflection.
```
ip rule add from PROSODY_ADDRESS/32 table sslh
ip rule add from OPENVPN_ADDRESS/32 table sslh
ip route add local 0.0.0.0/0 dev lo table sslh
```

Thats all!

**Comment by ftasnetamot** [comment]
Before digging any deeper into whatever: Please try to draw a better picture, showing your setup. If I spent time, looking into that picture, I am getting more and more confused.
How is the real traffic flowing, how are things connected.  Looks like, that you drawn just those things, you like, that they talk to each other.  If those hosts are container, they are hosted in another host. This host has a network setup, and no traffic can flow to any container from outside, without hitting the host first.
So just draw a network, like each container would be a separate box, connected with cables. Draw connections coresponding to your network setup in for your environment. Are they connected through dedicated virtual interfaces from the host? Are there one or more bridges involved? A bridge is in a network diagram something like a hub or switch.
A network can't be show as a box round a few servers, a network has connections.
When you have drawn that picture, that should include hints about the default gateway from each instance, make yourself familiar, how the traffic might flow, that will help you, making the right assumptions.
Next: Setup sslh as a forwarding proxy, just without "--transparent", if that is not working, check your connectivity and routing.  Dont have any of those rules in place, which should support transparent proxying. Just plain forwarding proxy.  If that works, transparent proxy should also work. If that is not working, search where the connectivity problem is!


When drawing tcp connections: Please don't write the destination port number to origin interfaces, that hurts. The source port of all those connections is random chosen from the ephemeral port range. Watch your connections with netstat and you will see that.

**Comment by ftasnetamot** [comment]
Again, its no problem, how do you assign a second ip address. So you are using the old way, where the interface gets subinterfaces added, like ens18:0 etc. 
**But again: Is non transparent proxyying working, without any routing/firewall rules beeing in place?**

If non transparent proxying is not working, we don't need to go further in configuration details.

**Comment by ftasnetamot** [comment]
If it works with forwarding proxy, and all your hosts are in a bridged network, follow the scenario 3.
In this case you need no dummy interface, but the routing deflection on the target hosts, pointing back to the sslh host!
Look to the pending pull request!

**Comment by ftasnetamot** [comment]
> 'm not sure about the meaning of the term "forwarding proxy"  ...
Just a proxy, which is forwarding connections and acts instead of the client. The transparent proxy hides it existence, while the classic proxy plays the role from the "man in the middle".
> I already took a look at the diagram from your pull request but I'm afraid I wont be able to compose the "special routing rule" you mentioned in it on my own, due to my lack of understand regarding routing and iptables/netfilter.

There is no iptables/netfilter in this solution. Forget about that. It is just two routing rules.

> Would you mind trying to explain to me why scenario 2 wouldnt work with the hosts being on a bridged network?

Because you have not drawn a network diagram, showing how your virtual servers are connected together and how routing works.  The bridge is not the reason, the reason is, that your router is tied to the bridge.
If the bridge would only connect an outgoing interface of your sslh host and the single interfaces of the destination hosts, while the sslh host only is connected with a front facing interface to the router, it will be scenario 2!

When that is right, that all servers are tied to a bridge, where also your router is connected to, your setup is scenario 3.
The targets have their own default gateway to the internet, and therefore the connection back would flow like the dotted line, which will not work.

**Comment by ftasnetamot** [comment]
I assume, that your network looks like this:
```
                       .................................
                       .      server hosting           .
                       .      the containers           .
                       .             |                 .
                       .             |                 .
 internet-------ROUTER-----+----+----+----------+------. 
                       .   |         |          |      .  
                       .  sslh    prosody    openvpn   .
                       .  host     host        host    .
                       .................................
```


>How am I supposed to show in a diagram how routing works in this setup if I have no idea how routing works?
**you REALLY should read some basic documents, about routing, tcp/ip  and system configuration, before connecting devices to the internet!!**
>Another question of understanding: Are you referring to my isp router or to the sslh vm with the term router?
Why this should be a router?  It looks like a router from your first wrong picture, but that is one system in a row of others.
They can all talk to each other, but talking to the internet their gateway out is your router.
Are you driving through public streets, following signs, telling you, which street you should take?
In my early network years, I liked driving through France, because there was always one additional destination: **toutes directions**. This concept of traffic routing I saw in most other european countries much later. This is telling "other directions", and so most crossroads in the streets have perfect routing tables! Default gateway means, all other destinations go here!

Think about (virtual) servers as Middle Ages Cities, having only some City Gates. Those are the entrys and exits for all traffic, and interfaces are those gates. Hubs, Switches, Bridges or Cables are the streets. Routers are bigger or smaller crossroads, where traffic has to decide, how to go and opposite to reality, all packets are following the signs!

Your problem is not sslh configuration, your problem is your fundamental understanding of basics. You opened that post 18 month ago, and still lacking fundamental basics of setting up things.

How you can be sure, that your systems are secure and cannot be abused?

This will be my last answer, you have all pieces to make it working. Go and learn basics, please!
