### ISSUE TITLE
Transparent proxy blocks the normal port

### ISSUE THREAD

**Issue by Yamakaky** [yrutschle/sslh#39]
The current iptables directive recommended in the README for transparent proxying targets to wide.

``` bash
iptables -t mangle -A  OUTPUT -p tcp -o eth0 --sport 22 -j SSLH
```

As it is, all the outgoing packets from port 22 (ssh daemon) are marked (and treated specially). The problem is that it also marks the connexions made directly to the 22 port, so the only way to ssh is via the sslh port. It should also permit direct connexions to the 22 port.

**Comment by Stenudd** [comment]
So here is a working solution for the previous transparent rules if you are routing to localhost like this

```
sslh --listen 0.0.0.0:443 --ssh localhost:22 ...
```
```
listen:
(
    { host: "0.0.0.0"; port: "443"; keepalive: true; }
);

protocols:
(
     { name: "ssh"; service: "ssh"; host: "localhost"; port: "22"; fork: true; }
     ...
);
```

Say your servers interface ip is 192.168.0.10 and you have this rule:
> iptables -t mangle -A OUTPUT -p tcp -o eth0 --sport 22 -j SSLH

tcpdump now shows outgoing LAN IP addresses from ssh server on port 22 on the **loopback** interface:
192.168.0.10.22 > 12.34.56.78.54321

since sslh and the ssh server communicates via localhost / 127.0.0.1 means that packages from 192.168.0.10 is to someone who connected directly towards port 22 and not 443, you can just apply another rule which prevents them from being routed towards the loopback interface

> iptables -t mangle -A OUTPUT -p tcp -o eth0 -s 192.168.0.10 --sport 22 -j ACCEPT
> iptables -t mangle -A OUTPUT -p tcp -o eth0 --sport 22 -j SSLH
