### ISSUE TITLE
tinc doesn't actually work

### ISSUE THREAD

**Issue by andrewshadura** [yrutschle/sslh#42]
Trying to connect to server (x.y.z.t port 655)
    Using proxy at proxy.company.fr port 1080
    Connected to server (x.y.z.t port 655)
    Proxy request granted
    Connection closed by server (x.y.z.t port 655)
    Closing connection with server (x.y.z.t port 655)
    Could not set up a meta connection to server
    Trying to re-establish outgoing connection in 5 seconds
    Trying to connect to server (x.y.z.t port 655)
    Using proxy at proxy.company.fr port 1080
    Connected to server (x.y.z.t port 655)
    Proxy request granted
    Connection closed by server (x.y.z.t port 655)
    Closing connection with server (x.y.z.t port 655)
    Could not set up a meta connection to server
    Trying to re-establish outgoing connection in 10 seconds

See also http://www.tinc-vpn.org/pipermail/tinc/2011-November/002799.html

**Comment by yrutschle** [comment]
On Fri, Feb 20, 2015 at 06:35:55AM -0800, Andrew Shadura wrote:
>     Trying to connect to server (x.y.z.t port 655)
>     Using proxy at proxy.company.fr port 1080
[...]

What's happening on the sslh side... with -v and maybe
tcpdump?

> See also http://www.tinc-vpn.org/pipermail/tinc/2011-November/002799.html

This has been corrected a long long time ago, what version
are you using?

**Comment by gbisheimer** [comment]
I have just configured sslh for Tinc using the available REGEX expressions to forward request to 2 Tinc servers based on client names. Did't know that Tinc protocol was included. I had no problems so far.

**Comment by yrutschle** [comment]
Considering the lack of response from OP and your feedback, I'll close this issue. Thanks!

**Comment by kub1x** [comment]
Hey, sorry for reopenning, but I'm getting the same error on my client so for documentation purpose, I'll ask here. Since I could not connect, I've looked to logs on server and seen errors like: `Peer 1.2.3.4 port 1234 had unknown identity (kub1x@myvpn)` and that `/etc/tinc/myvpn/hosts/kub1x` file is missing. 

To better explain the situation I want to connect to my cluster (all nodes in `myvpn` so far) from my workstation `kub1x`. Do I really have to put `kub1x` config file to `/hosts` directory on all the servers? Or how can I connect to tinc as client only? I do have configs (those with public key and addresses) collected from all the servers on my workstation. 

Hope the question is clear this way.

**Comment by yrutschle** [comment]
Hi, Sorry no it's not clear to me how sslh is involved in
your setup. Your description suggest your tinc setup isn't
working, which is not sslh-related.
