### ISSUE TITLE
Issue ripe for deletion - only arrogance and condescense, no help

### ISSUE THREAD

**Issue by njs95** [yrutschle/sslh#457]
Issue ripe for deletion - only arrogance and condescense, no help

**Comment by ftasnetamot** [comment]
> Does this work with SSLH in docker or is it only for a local installation?

**READ** it, please!
You will find this sentence:
_This concept can also be adapted for several setups, where the sshd (or any other target service) is running in a container, kvm-virtual machine, etc. Precondition is, that the target system is the next hop and uses the sslh-hosting system as default gateway._

The new setup works for almost every setup, and I tried to explain, why and how it works.
And also here:  Before we know, how you real network  scenarion looks like, there is now answer possible.
Read the tow documents, try to understand, which of the routing scenarios may match your Traefik container and draw a network plan.
My guess is, that you forget the firewall-packetmarking and routing setup, if you followed the traditional way.  The only thing, which is new to my setup is:
- that you don't need to enable routing localnet, which implies security risks
- you use a dedicated dummy interface, for the target applications with a own /32 ip address, you can choose arbitrarly
- because of this dedicated ip its no longer needed, marking packets with firewall rules for routing
- routing is done based on the uniqe IP

And the basic thing is: If you have your network plan, where you can see, which ways packets will take back to a client, you can decide, if you need a configuration following scenario 1, 2 or 3.

**Comment by njs95** [comment]
https://github.com/yrutschle/sslh/blob/master/doc/simple_transparent_proxy.md

This is the guide I'm following. As far as I can see it does not contain the word docker. And this one I have read several times.
Maybe you want me to **READ** something else? Saying "you tried to expalin", probably yes.

The problem I'm having is that I'm not a computer scientist or network engineer by trade, and while I can follow a guide, I do not have some grand old network plan, and I don't know what a tow document is. For sslh everything only contains snippets from different configurations and years.

For example, I played around with the packaged version for a while, before I noitced it hadn't been updated in 9 years or so.

The first link is the thing I tried, and I tried it both with the docker version (no packets going through at all if I set the destinations to 192.168.255.254) and I spent my whole night compiling the standalone version, but here I run into half a dozen different error messages, the most prominent of them: 
`Landlock: Failed to create a ruleset`

**Comment by ftasnetamot** [comment]
docker is a **product** name, for a container solution, and you will find the word container!
**I** used abstractions and no product names for containers, kvm instances, virtualisation systems in this documentation.

You need not to be an computer scientist, but you **NEED** to have a understanding, what you are trying to construct.
For network related setups, a network plan, showing how all the components are tied together and how the traffic is flowing in between, is mandatory for configuration and for further help.

And the best way setting this up is: First get it working in the standard way, without transparency. If this is not working, fix those problems first. If everything is working in standard mode, set up the dummy interface, tie your backend application to this interface, but keep the configuratin still intransparent.  If this is not working, check all your settings, as you made an mistake in reconfiguration.  In the next step, switch sslh to transparent.  If this is now not working, you need to recheck your network plan and figure out, how the packets from the target applications will be routed back.

**Comment by njs95** [comment]
Well I had it working with limited transparency and with the localroute=1 trick. As I explained in the first post.

Regarding the dummy interface: 
In the background I keep trying things, ander after creating /etc/network/interfaces and pasting this
```
auto dummy0
iface dummy0 inet static
    address 192.168.255.254/32
    pre-up modprobe dummy
    ## Attention! with kernels, not automatically creating a dummy0
    ## interface after module loading the following line should be:
    ## pre-up modprobe dummy; if [ ! -e /sys/class/net/dummy0 ]; then ip link add dummy0 type dummy ; fi
    post-up ip rule add from 192.168.255.254 table sslh
    post-up ip route add local 0.0.0.0/0 dev dummy0 table sslh
    pre-down ip route del local 0.0.0.0/0 dev dummy0 table sslh
    pre-down ip rule del from 192.168.255.254 table sslh
```

Neither ifconfig nor ip link show display a dummy0 interface. I'm using Ubuntu-Server 22.04, Kernel 5.15.0-116-generic.
Is this expected behaviour?

Also you say "tie" your backend application to this interface? What does this mean?

**Comment by ftasnetamot** [comment]
What is "limited" transparency?  I know transparent and nontransparent aka intransparent mode. But limited transparency?
What happens if you bring the interface up with `ifup dummy0`?
And again:  This documentation is abstract and works mostly with most basic linux distributions.
However, if you are using things like network manager with netplan, configuration needs to go to other locations, So check your used configuration tools and apply the configuration to the right place.

> Also you say "tie" your backend application to this interface? What does this mean?
Really?  You can configure your application and tell, at which interface at which port it listens. The application uses the `bind()` system call, to tie or bind to this address on the corresponding interface. 

In a network plan, there is no pre/postrouting. A network plan just looks like a street map, which shows, how single addresses (houses) are connected together, and which routes (streets) people can use, to go from a to b and back.

pre/postrouting are firewall concepts, and my configuration method, does not need any firewall support. It only need routing.

If you have a plan, just show it, with all interfaces of the related systems, with their ips.

For sslh you are fine with the debian distributed versions.  I have transparent sslh running on ubuntu 20.4, debian bookworm, debian buster and bullseye and devuan daedalus just with the distribution sslh. There are setups, where I connect to kvm-virtual-hosts.

>If I do not have an exact preset that works in principle where I can adjust my ip addresses or interfaces like a monkey, I will never get the syntax right.

With this preconditions, please stop setting up servers in the internet!

**Comment by njs95** [comment]
> What is "limited" transparency? I know transparent and nontransparent aka intransparent mode. But limited transparency?

I explained this in the original post. Worked for ssh, did not work for traefik and the services behind it. Maybe I should have said partial instead of limited?

> However, if you are using things like network manager with netplan, configuration needs to go to other locations, So check your used configuration tools and apply the configuration to the right place.

I use whatever Ubuntuserver 22 shipped with, and never touched a thing.

> For sslh you are fine with the debian distributed versions.

So these nine years don't matter at all for security, functionality, or anything like that?
In any case, I'd love to run it in docker if I can, that way it's easier to keep up to date than to compile it yourself every time.
I'll attach a jpeg of a rudimentary plan, but I didn't have any fancy software for that installed, so paint it is.



> With this preconditions, please stop setting up servers in the internet!

What a horrible attitude to live your life.
If you aren't a cook, stop cooking, it's dangerous.
If you aren't a doctor, stop taking pills against headache.
If you can't assemble a combustion engine from ground up with no tools, stop driving your car.
![sslhplan](https://github.com/user-attachments/assets/b4d8c6af-ec86-4c77-9acf-7aa330ea671f)

**Comment by ftasnetamot** [comment]
> What a horrible attitude to live your life. If you aren't a cook, stop cooking, it's dangerous. If you aren't a doctor, stop taking pills against headache. If you can't assemble a combustion engine from ground up with no tools, stop driving your car. 

**What a horrible attitude** asking for help, and insulting people spending their own free time assisting you!

- If you don't know the difference between poison and spices, stop cooking!
- If you don't know, why you are having headache, and the side effects of your pills, stop taking them
- if you have no plan from traffic rules and no drivers license, please don't drive a car!
**Unsecure servers are theatening us all!** If you ask for help from your point of knowledge you need to accept at least critics!

 Your plan shows, that you have no clue what you are doing.  
-How many interfaces are on your router/switch, what are the related addresses.
- Your docker has no interface at all?
- on which interface is OpenVPN, sshd and service 2 listening? How is the routing to/from docker happening?

Try to create an plan, which really shows **all** interfaces and *ip addresses**, (you can name them ip1, ip2, but it must be clear, to which network they belong) and on which of those interfaces all the applications are listening.
Look at my extended [documentation](https://github.com/yrutschle/sslh/blob/master/doc/scenarios-for-simple-transparent-proxy.md) with the three scenarios.

And again:
- Is it working without transparency?
- Is it working without transparency, and the targets now reside on dummy interface?

But expect no further help from me! Bye

**Comment by njs95** [comment]
I knew that from your very first sentence, but I like to try. Bye

**Comment by njs95** [comment]
Because traefik can be a handful, and because TLS can be weird. I set up a nginx:demo container and a http forward in sslh.

```
version: '3.8'
services:
  nginx:
    image: nginxdemos/nginx-hello
    ports:
      - 192.168.255.254:8080:8080
```
```
version: "3"

services:
  sslh:
    build: https://github.com/yrutschle/sslh.git
    container_name: sslh
    environment:
      - TZ=Berlin/Europe
    security_opt:
      - no-new-privileges=false

    cap_add:
      - NET_ADMIN
      - NET_RAW
      - NET_BIND_SERVICE
    #sysctls:
     # - net.ipv4.conf.default.route_localnet=1
     # - net.ipv4.conf.all.route_localnet=1
    command: --listen 192.168.172.55:443 --transparent --foreground --ssh 192.168.255.254:22 --tls 192.168.255.254:8443 --http 192.168.255.254:8080 --verbose=3
    network_mode: host
    ports:
      - target: 443
        published: 443
        protocol: tcp
        mode: host

    restart: unless-stopped
```
SSH is working.
I can reach the demo under port 8080 from the network (when I don't bind it to dummy0), so it's working in principle.
If I go through sslh on serverip:443, HTTP is not working. I am telling the browser specifically to use http under port 443, and a http probe is detected but not forwarded.

```
probed for http: PROBE_MATCH

trying to connect to 192.168.255.254:http-alt family 2 len 16

http: lost incoming connection
```
If I run curl 192.168.255.254:8080 on the host I actually get a result that indicates I reached the nginx:demo.

So, eth0 can reach sslh in docker, sslh can reach dummy0, and dummy0 can reach the nginx demo.
But I can't go all the way with a real http connection (or https for that matter).
At which point does my routing break down, what do I have to adjust?

**Comment by yrutschle** [comment]
I think ample help was provided here...
I'll close this thread now.
