### ISSUE TITLE
Recent commit to config_parse() breaks cmdline_config()

### ISSUE THREAD

**Issue by hogarthj** [yrutschle/sslh#58]
This commit prevents cmdline_config() working in the expected manner:

https://github.com/yrutschle/sslh/commit/5886bd2d43db3ee6a9ae58e3e47c34e07cf80f00

The function is meant to try /etc/sslh/sslh.cfg first if no configuration is given and then fall back to /etc/sslh.cfg and then if still no configuration fail.

Since config_parse() as of this commit bails on a nonexistent file then if no config is provided /etc/sslh/sslh.cfg will be tried and when that's not found it will bail rather than test for /etc/sslh.cfg next. 

We should either change cmdline_config to only check one file (or no default file) or revert the commit so that cmdline_config() still works as expected.

**Comment by yrutschle** [comment]
Indeed. I just committed new, hopefully working, code...

**Comment by hogarthj** [comment]
It tripped me up testing some systemd socket activation stuff ;)

On the systemd mailing list someone suggested writing a systemd-generator so that the .socket file doesn't override config in sslh.cfg but rather it all gets merged ...

Coming on pretty well :)

**Comment by yrutschle** [comment]
On Tue, Jul 28, 2015 at 08:08:43AM -0700, hogarthj wrote:
> It tripped me up testing some systemd socket activation stuff ;)

I added the previous patch because while integrating SNI I
got confused because sslh wouldn't complain when opening a
non-existant file...

Eventually we'll get it right...

> On the systemd mailing list someone suggested writing a systemd-generator so that the .socket file doesn't override config in sslh.cfg but rather it all gets merged ...

I don't think I understand this, but I am yet to look at
what you posted. BTW I'm not ignoring you, but I guess I
need to upgrade my Debian to get systemd to see how it all
works.
