### ISSUE TITLE
auth.error: forward to [PROBE] failed:connect: Connection refused

### ISSUE THREAD

**Issue by benf33** [yrutschle/sslh#83]
I run sslh v1.17 on Openindiana Hipster and I have the following issue in the log popping regularly.

```
Mar 14 20:07:59 aurore sslh[29117]: [ID 632210 auth.error] forward to ssl failed:connect: Connection refused
Mar 14 20:31:20 aurore sslh[29117]: [ID 632210 auth.error] forward to ssl failed:connect: Connection refused
Mar 14 20:51:11 aurore sslh[29117]: [ID 632210 auth.error] forward to ssl failed:connect: Connection refused
```

or for openvpn, I have as well the same message.

Config is 

```
verbose: false;
foreground: false;
timeout: "2";
user: "nobody";
pidfile: "/var/run/sslh.pid";


# Change hostname with your external address name.
listen:
(
    { host: "10.1.1.27"; port: "443"; }
);

protocols:
(
     { name: "ssh"; service: "ssh"; host: "localhost"; port: "22"; probe: "builtin"; },
     { name: "openvpn"; host: "localhost"; port: "1194"; probe: "builtin"; },
     { name: "ssl"; host: "localhost"; port: "8443"; probe: "builtin"; }
);
```

I ran it once on verbose+foreground, it gave me this

```
# /usr/sbin/sslh -F /etc/sslh.cfg
Using /etc/sslh.cfg
ssh addr: aurore:ssh. libwrap service: ssh family 26 26
openvpn addr: aurore:openvpn. libwrap service: (null) family 26 26
ssl addr: aurore:8443. libwrap service: (null) family 26 26
listening on:
        aurore:https
timeout: 2
on-timeout: ssh
listening to 1 addresses
turning into nobody
sslh-fork oi-20151003-515-g0c1010e-dirty started
accepted fd 5
**** writing deferred on fd -1
probing for ssh
probing for openvpn
connecting to aurore:openvpn family 26 len 32
forward to openvpn failed:connect: Connection refused
connecting to aurore.local:openvpn family 2 len 16
connection from 161-65-50-133-ip.gns.cri.nz:47359 to aurore:https forwarded from aurore.local:57100 to aurore.local:openvpn
flushing deferred data to fd 4
^C
```

Otherwise it is working fine to forward but I have a issue when kill sslh but this will be another issue I guess.
Ben

**Comment by yrutschle** [comment]
On Mon, Mar 14, 2016 at 01:46:54PM -0700, benf33 wrote:
> Mar 14 20:07:59 aurore sslh[29117]: [ID 632210 auth.error] forward to ssl failed:connect: Connection refused

sslh tried to connect to httpd, and the connection failed.

If it works "most of the time", I'd say this will be the
httpd server refusing connections (because too many of them
and there is a limitation?), or maybe the kernel refusing
the connection because of a lack of resources.

Either way, it doesn't feel like this is a sslh issue.

How does it handle repeated connections directly to httpd,
e.g. using wget localhost, to see if that too fails
sometimes as well?

**Comment by benf33** [comment]
This would be because HTTPD (ssl) refuse to answer. Interesting. Browsing on the website doesn't bring any issue.
But what about openvpn and the 
```
connecting to aurore:openvpn family 26 len 32
forward to openvpn failed:connect: Connection refused
connecting to aurore.local:openvpn family 2 len 16
```

**Comment by yrutschle** [comment]
On Mon, Mar 14, 2016 at 04:23:16PM -0700, benf33 wrote:
> connecting to aurore:openvpn family 26 len 32
> forward to openvpn failed:connect: Connection refused
> connecting to aurore.local:openvpn family 2 len 16

Same thing: are you sure you're not running very low on
resources and servers have to drop connections?

As far as I know 'Connection refused' means either there is
no server listening, or the server isn't able to accept a
connect. If some connections are accepted, then the server
is in fact listening, which would make me question the
resources available to the server.

**Comment by benf33** [comment]
Thanks, I'll try to make more intensive tests when I have some time and am not relying on sslh to access to the machine :-)

**Comment by baptx** [comment]
I had the same error with OpenVPN Access Server on my Linux Virtual Private Server. The error message `forward to openvpn failed:connect: Connection refused` was displayed in `/var/log/syslog`. I fixed the problem by replacing `127.0.0.1:1194` by my VPN IP address followed by `:1194` in `/etc/default/sslh`.
Is it normal that I cannot use 127.0.0.1? Is there no performance impact by replacing 127.0.0.1 with my VPN IP address? (e.g. I am not sure if external requests are done, the IP address of my VPN may be linked to a local interface since the IP address is displayed when I type the command `ip addr`).

**Comment by yrutschle** [comment]
I guess you set up OpenVPN to listen to the IP address you don't mention, and not 127.0.0.1. You can see who's listening where with:
```
netstat -lpt
```
If OpenVPN is not listening to 127.0.0.1:1194, that's your issue. I don't think there would be any performance penalty, though.

**Comment by yrutschle** [comment]
Also, I got an e-mail notification for your message 2 hours ago (meaning, April 7th 2020, mid-covid pandemic). Github indicates you posted July 27th 2019 (meaning, last year, mid-summer enjoying holidays away from home). I don't know what happened there :)

**Comment by baptx** [comment]
@yrutschle thanks, you probably disabled notifications for this issue (by default GitHub enables notifications automatically for an issue when you comment on it). That's why I updated my comment 2 days ago to mention you so you can receive a notification in case you did not see my comment.
Last year I used the default OpenVPN Access server configuration and now I used the default configuration of this OpenVPN installer script: https://github.com/Nyr/openvpn-install
So it looks like OpenVPN does not listen on localhost by default. I had to add "u" to the netstat command to see UDP ports.

**Comment by yrutschle** [comment]
I usually get notifications for all issues, being the repo owner and all... but it doesn't seem to be very reliable.

Ok, I'll close this issue then. I should probably start a FAQ with that netstat command, too...
